import { jsPDF } from "jspdf";
import { toDataURL } from "qrcode";

async function generateTicket(ticket) {
    const doc = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
    });

    // Background
    doc.setFillColor(245, 248, 255);
    doc.rect(0, 0, 210, 297, "F");

    // Border
    doc.setDrawColor(37, 99, 235);
    doc.setLineWidth(1);
    doc.roundedRect(8, 8, 194, 281, 4, 4);

    // Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.setTextColor(37, 99, 235);
    doc.text(ticket.eventName, 20, 25);

    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text("EVENT ENTRY PASS", 20, 33);

    // Divider
    doc.line(20, 38, 190, 38);

    // Attendee Details
    doc.setTextColor(0);
    doc.setFontSize(18);
    doc.text("Attendee", 20, 50);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(13);

    let y = 60;

    const details = [
        ["Name", ticket.name],
        ["Email", ticket.email],
        ["Ticket ID", ticket.ticketId],
        ["Booking ID", ticket.bookingId],
        ["Category", ticket.category],
        ["Date", ticket.date],
        ["Time", ticket.time],
        ["Venue", ticket.venue],
        // ["Seat", ticket.seat],
        ["Amount", `₹${ticket.amount}`],
        ["Status", ticket.paymentStatus],
    ];

    details.forEach(([key, value]) => {
        doc.text(`${key}: ${value}`, 20, y);
        y += 8;
    });

    // QR Code
    const qrString = JSON.stringify({
        ticketId: ticket.ticketId,
        bookingId: ticket.bookingId,
    });

    const qr = await toDataURL(qrString);

    doc.addImage(qr, "PNG", 145, 50, 45, 45);

    doc.setFontSize(10);
    doc.text("Scan for Verification", 146, 100);

    // Information Box
    doc.setDrawColor(37, 99, 235);
    doc.roundedRect(20, 160, 170, 45, 3, 3);

    doc.setFont("helvetica", "bold");
    doc.text("Important Instructions", 25, 165);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);

    const instructions = [
        "• Carry a valid Government ID.",
        "• QR Code is mandatory for entry.",
        "• Ticket is non-transferable.",
        "• Entry closes 30 minutes after start.",
        "• Screenshot copies are not accepted.",
    ];

    let lineY = 175;

    instructions.forEach((item) => {
        doc.text(item, 25, lineY);
        lineY += 6;
    });

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(120);

    doc.text(
        "Generated by MindVerse Event Management System",
        105,
        285,
        { align: "center" }
    );

    return Buffer.from(doc.output("arraybuffer"));
}

export default generateTicket;